### PR TITLE
OpenImagePlusPlugin opens multiple open ImagePlus's

### PR DESCRIPTION
**Pull request by bogovicj**
I wanted this for myself, so just went for it.
See #7.

### CODE REVIEW

**Comment by bogovicj** [comment]
@tpietzsch ,

This pull requests changes `Plugins>BigDataViewer>Open Current Image`.
It now brings up a dialog with a check boxes next to the names of all open images, to start only the current image is checked.  After clicking "OK" all checked images will be open in a single bdv window.

I talked to @axtimwalde  just now, who suggested these alternative possibilities :
1. Keep the existing plugin and have the new functionality in a different plugin with a different name
2. Keep the existing plugin, but autodetect open bdv windows, and ask the user if they want to add to the existing window.

**Comment by bogovicj** [comment]
Actually, I just noticed that this PR sometimes has a `SetupAssignment` issue.  Let me deal with it before merging.

Specifically, the issue is that sometimes multiple sources are grouped in the "Brightness and Color" dialog and can't be un-linked.

**Comment by bogovicj** [comment]
@tpietzsch

This is ready for you to look at whenever you have a rare moment.  
Fwiw, I've found this really useful.

**Comment by tpietzsch** [comment]
Thanks @bogovicj!
Merged via 7a664439223fcfedccf692023ec399a387721f38

**Pull request closed without merging**
